### PR TITLE
Support for TYPEOF fields for polymorphic fields

### PR DESCRIPTION
**Pull request by jongpie**
https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_typeof.htm

### CODE REVIEW

**Comment by jongpie** [comment]
Sample usage for querying tasks, using the WhoId polymorphic field (contact & lead objects):

```
Map<Schema.SobjectType, List<Schema.SobjectField>> fieldsBySobjectType = new Map<Schema.SobjectType, List<Schema.SobjectField>>();

// Contact fields
List<Schema.SobjectField> contactFields = new List<Schema.SobjectField>{
    Schema.Contact.Id, Schema.Contact.Name, Schema.Contact.AccountId
};
fieldsBySobjectType.put(Schema.Contact.SobjectType, contactFields);

// Lead fields
List<Schema.SobjectField> leadFields = new List<Schema.SobjectField>{
    Schema.Lead.Id, Schema.Lead.Name, Schema.Lead.Company, Schema.Lead.LeadSource
};
fieldsBySobjectType.put(Schema.Lead.SobjectType, leadFields );

// Query the task object
SobjectQueryBuilder query = new SobjectQueryBuilder(Schema.Task.SobjectType)
    .addPolymorphicFields(Schema.Task.WhoId, fieldsBySobjectType)
    .filterWhere(Schema.Task.WhoId, Soql.Operator.NOT_EQUAL_TO, null);

System.debug(query.getQuery());
System.debug(query.getResults());
```

**Comment by jongpie** [comment]
I've spent some more time on this and there are now currently 3 main ways to include polymorphic fields

1. Standard addField methods - no special polymorphic functionality is leveraged
    ```
    new SobjectQueryBuilder(Schema.Task.SobjectType)
        .addField(Schema.Task.WhoId);
    ```

2. addPolymorphicFields method with 1 parameter - all possible related fields are automatically added to your query (like Who.Alias, Who.Email, Who.Id, Who.Name, Who.Type, etc).
    ```
    new SobjectQueryBuilder(Schema.Task.SobjectType)
        .addPolymorphicFields(Schema.Task.WhoId);
    ```

3. addPolymorphicFields method with 2 parameters - this allows you to specify sobject fields to return. For any unspecified sobject types, a fallback 'ELSE' statement is automatically added to return all possible related fields (like Who.Alias, Who.Email, Who.Id, Who.Name, Who.Type, etc).
    ```
    Map<Schema.SobjectType, List<Schema.SobjectField>> fieldsBySobjectType = new Map<Schema.SobjectType, List<Schema.SobjectField>>();

    // Lead fields
    List<Schema.SobjectField> leadFields = new List<Schema.SobjectField>{
        Schema.Lead.Id, Schema.Lead.Name, Schema.Lead.Company, Schema.Lead.LeadSource
    };
    fieldsBySobjectType.put(Schema.Lead.SobjectType, leadFields );
    new SobjectQueryBuilder(Schema.Task.SobjectType)
        .addPolymorphicFields(Schema.Task.WhoId, fieldsBySobjectType);
    ```

**Comment by marcellcsiszar** [comment]
Sorry for the late answer. Looks good, I would love to see it in master branch.

**Comment by jongpie** [comment]
@marcellcsiszar sorry for the late response - I meant to merge this last year, but better late than never 😄  I've now merged this into master

**Comment by marcellcsiszar** [comment]
no prob, I'm really glad about you made this enhancements. I had no chance to use your packages elsewhere since than. I hope at some point in the near future I will have chance to try out your changes. :)

**Pull request merged**
