### PR TITLE
Added nested conditional filter support

### PR DESCRIPTION
**Pull request by jamessimone**

### CODE REVIEW

**Comment by jongpie** [comment]
@jamessimone I just reviewed this again, and I love it! I think I'm good with the class & enum names - I'll go ahead and merge this into my branch for PR #39, and then I'll release the new packages this week.

Thanks again for adding this!

**Comment by jamessimone** [comment]
Awesome, sounds good!

**Comment by jongpie** [comment]
@jamessimone I'm going to revert & reopen this PR for the moment - it looks like there wasn't an assert in the new test method, so I added `System.assertEquals(expected, actual.getQuery());` (plus a small change to include the `Name` field in the expected query, since `Query` auto-adds the name field.... apparently), and the generated `where` clause is a bit jumbled.

- **Expected**: `SELECT Id, Name FROM Contact WHERE LastName = :bindVar0 OR LastName = :bindVar1 OR (FirstName = :bindVar2 AND (LastName != :bindVar3 OR LastName != :bindVar4))
- **Actual**: `SELECT Id, Name FROM Contact WHERE (AND (FirstName = ':bindVar2' OR (LastName != ':bindVar3' LastName != ':bindVar4'))) AND (LastName = ':bindVar1') AND`

In the 'actual' value, there are some extra `AND` strings being added, and more notably, the ordering of the filter string is different. I think this is all related to some existing logic in the `SOQL` class that does some sorting on the list of `QueryFilter` when generating the query string via `Query.getQuery()`. It's been so long since I worked on some of this code, I don't remember why exactly it's doing the sorting, but I know it was a purposeful decision that probably made sense when it was added [5 years ago](https://github.com/jongpie/NebulaQueryAndSearch/commit/33a80ed122b6976fb05476978f54a0d59a04f25d)😅 ), and I don't want to risk breaking existing behavior by changing it right now. I'm planning to do a big refactor of the entire codebase over the coming weeks; I'll re-merge your changes once I've dived a little deeper into the code & done some cleanup.

**Comment by jamessimone** [comment]
Sure, makes sense!

**Pull request merged**
